# Generated by Django 5.2.1 on 2025-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_upload', models.FileField(upload_to='music/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_by', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Active Track?')),
                ('start_date', models.DateTimeField(blank=True, help_text='Date the track starts in the rotation', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Date the track ends in the rotation', null=True)),
            ],
        ),
    ]
