# Generated by Django 5.2.1 on 2025-06-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='start_date',
        ),
    ]
